name: Deploy to Server

on:
  push:
    branches:
      - master  # Adjust to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 93.127.206.2 >> ~/.ssh/known_hosts

    - name: Sync files to server
      run: |
        rsync -avz --exclude 'node_modules' --delete ./ root@93.127.206.2:/var/www/picraft
      env:
        RSYNC_RSH: ssh

    # - name: Copy .env file
    #   run: |
    #     ssh root@93.127.206.2 'cp /path/to/.env /var/www/picraft/.env'

    - name: Install dependencies and build project
      run: |
        ssh root@93.127.206.2 'cd /var/www/picraft && npm install && npm run build'

    - name: Restart PM2 process
      run: |
        ssh root@93.127.206.2 'pm2 restart picraft'
